# Starship configuration:
# https://starship.rs/config/

"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$direnv\
$env_var\
$crystal\
$kubernetes\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character
"""

add_newline = true

[[battery.display]]
threshold = 20

[directory]
truncation_length = 4
truncate_to_repo = true
truncation_symbol = '../'

[git_branch]
symbol = ' '

[git_commit]
only_detached = true

[git_status]
format = '(\[$untracked$staged$modified$renamed$deleted$stashed$conflicted$ahead_behind\] )'
untracked = '[?](#aaaaaa)'
staged = '[+](green)'
modified = '[~](#ff9933)'
renamed = '[»](#ff9933)'
deleted = '[-](red)'
stashed = '[\$](#904fac)'
diverged = '⇣$behind_count⇡$aheadcount'
conflicted = '[#](yellow)'

[golang]
symbol = ' '

[hostname]
ssh_only = true

[kubernetes]
disabled = true
style = '#70c0b1'
format = '[$symbol$context( \($namespace\))]($style) '
symbol = '☸ '

[lua]
symbol = ' '

[package]
symbol = '󰏗 '

[username]
show_always = false

